accounts/urls.py
from django.urls import re_path, path, include
from .views import *

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^profile/$', profile_view, name='profile'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^changepassword/$', change_password_view, name='change_password'),
    
]

webProject/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings
from home.views import *

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', home_view, name='home'),
    re_path(r'^accounts/', include('accounts.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    MAN = 'M'
    WOMEN = 'W'
    OTHER = 'O'
    SEX = (
        (MAN, 'MAN'),
        (WOMEN, 'WOMEN'),
        (OTHER, 'OTHER'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User')
    cell_phone = models.CharField(max_length=11, verbose_name='Phone no', blank=True)
    location = models.CharField(max_length=250, verbose_name='Location', blank=True)
    career = models.CharField(max_length=250, verbose_name='Career', blank=True)
    sex = models.CharField(max_length=1, default=3, choices=SEX, verbose_name='Sex', blank=True)
    about = models.TextField(max_length=500, blank=True, verbose_name='About')
    birthday = models.DateField(blank=True, verbose_name='Birthday', null=True)



def create_user_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = Profile(user=user)
        user_profile.save()


post_save.connect(create_user_profile, sender=User)

home/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='Kullanıcı Adı')
    password = forms.CharField(max_length=100, label='Parola', widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Kullanıcı adını veya şifreyi yanlış girdiniz!")
        return super(LoginForm, self).clean()


class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100)
    email = forms.EmailField()
    password1 = forms.CharField(max_length=100, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=100, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Parolalar eşleşmiyor')
        return password2


class ProfileForm(forms.ModelForm):
    MAN = 'M'
    WOMEN = 'W'
    OTHER = 'O'
    SEX = (
        (MAN, 'MAN'),
        (WOMEN, 'WOMEN'),
        (OTHER, 'OTHER'),
    )
    cell_phone = forms.CharField(max_length=11,label='Phone no',required = False)
    sex = forms.CharField(widget=forms.Select(choices=SEX),required = False)
    about = forms.CharField(widget=forms.Textarea, max_length=500, label='About',required = False)
    birthday = forms.DateField(
        
        widget=forms.widgets.DateInput(attrs={
            'class': 'datepicker',
            'type': 'date'
            }),
         label='Birthday',
         required = False)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'birthday',
            'sex',
            'cell_phone',
            'about'
        ]
        help_texts = {
            'username': None,
            
        }

accounts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout,update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, RegisterForm, ProfileForm
from .models import Profile
from .forms import ProfileForm


def login_view(request):
    if request.user.is_authenticated:
        return redirect('home')
    form = LoginForm(request.POST or None)
    content = {
        'form': form,
        'title': 'Giriş yap'
    }
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('/accounts/profile')

    return render(request, 'accounts/form.html', content)

def register_view(request):
    if request.user.is_authenticated:
        return redirect('home')
    form = RegisterForm(request.POST or None)
    content = {
        'form': form,
        'title': 'Üye ol'
    }
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        user.is_staff = True
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        return redirect('home')
    return render(request, 'accounts/form.html', content)


def logout_view(request):
    logout(request)
    return redirect('home')


def profile_view(request):
    data = {
        'sex': request.user.profile.sex,
        'about': request.user.profile.about,
        'cell_phone': request.user.profile.cell_phone,
        'birthday': request.user.profile.birthday
            }

    user_profile_form = ProfileForm(request.POST or None, instance=request.user, initial=data)
    content = {
        'form': user_profile_form,
        'title': 'Güncelle'
    }

    if request.method == 'POST':
        if user_profile_form.is_valid():
            user_profile_form.save(commit=True)
            sex = user_profile_form.cleaned_data['sex']
            about = user_profile_form.cleaned_data['about']
            cell_phone = user_profile_form.cleaned_data['cell_phone']
            birthday = user_profile_form.cleaned_data['birthday']

            request.user.profile.sex = sex
            request.user.profile.birthday = birthday
            request.user.profile.cell_phone = cell_phone
            request.user.profile.about = about
            request.user.profile.save()

    return render(request, 'accounts/form.html', content)

def change_password_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  
            return redirect('home')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password_form.html', {
        'form': form
    })

home/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_object_or_404, redirect, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime
from django.contrib.auth.models import User
# Create your views here.


def home_view(request):
    if request.user.is_authenticated:


        context = {
            'isim':  request.user,
        }
    else:
        return redirect('accounts:login')

    return render(request, 'home.html', context)

templates/accounts/change_password_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block body %}

<div class="col-md-8 col-md-offset-3">


      <form method="POST" enctype="multipart/form-data">

          <div class="input-field col s8 z-depth-3" >
            {% csrf_token %}
            {{form|crispy}}
          <input class="waves-effect waves-light btn" type="submit" value="Şifreyi Değiştir">
          <hr>
          </div>
      </form>


</div>

{%endblock %}

templates/accounts/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{%block body %}

<div class="col-md-8 col-md-offset-3">


      <form method="POST" enctype="multipart/form-data">

          <div class="input-field col s8 z-depth-3" >
            {% csrf_token %}
            {{form|crispy}}


          <input class="waves-effect waves-light btn" type="submit" value="{{ title }}">
          {% if  title == 'Giriş yap' %}
          <a class="waves-effect waves-light btn" href="{% url 'accounts:register' %}" >Kayıt ol</a>
          <a class="pull-right" href="{% url 'password_reset' %}" >Şifremi unuttum</a>

          {% endif %}
          <hr>
          </div>
      </form>


</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
   <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.4/js/materialize.min.js"></script>

<script>
(function($){
  $(function(){
    // Plugin initialization
    $('select').not('.disabled').formSelect();
    $('.datepicker').datepicker({yearRange:100,container:});
  });
})(jQuery); // end of jQuery name space
</script>
{%endblock %}

templates/base.html
{%load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title>
        {%block title %}
            Website
        {%endblock %}
    </title>
</head>
<body>

    {% include 'header.html' %}
    <div class="container container-fluid">
      <div class="row  ">
        {%block body %}
        {%endblock %}
      </div>

    </div>


    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav>
  <div class="nav-wrapper  indigo darken-3" >
    {% if  request.user.is_authenticated %}
    <a href="{% url 'home' %}" class="brand-logo"><i class="material-icons" class="left">cloud</i>Website</a>
    {% else %}
    <a href="{% url 'accounts:login' %}" class="brand-logo"><i class="material-icons" class="left">cloud</i>Website</a>
    {% endif %}

    <ul id="nav-mobile" class="right hide-on-med-and-down">

 
      {% if request.user.is_authenticated %}
          <li><a href="{% url 'accounts:change_password' %}">Şifre Değiştir</a></li>
          <li><a href="{% url 'accounts:profile' %}"class="material-icons">account_box</a></li>

      {% endif %}

      {% if not request.user.is_authenticated %}
          <li><a href="{% url 'accounts:register' %}" >Kayıt ol</a></li>
          <li><a href="{% url 'accounts:login' %}">Giriş</a></li>
      {% else %}
          <li><a href="{% url 'accounts:logout' %}" class="material-icons">exit_to_app</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/home.html
{% extends 'base.html' %}



{% block body %}

    <div class="row purple lighten-5 card">
        <div class="col s4 ">
                <h2 class="center">Hoşgeldin</h2>
                

        </div>
        <div class="col s4 ">
                <p class="center">Kullanıcı Adı: {{ user.username }}</p>
                <p class="center">Ad: {{ user.first_name }}</p>
                <p class="center">Soyad: {{ user.last_name }}</p>
                <p class="center">email: {{ user.email }}</p>
                <p class="center">Doğum günü: {{ user.profile.birthday }}</p>
                <p class="center">Cinsiyet: {{ user.profile.sex }}</p>
                <p class="center">Cep telefonu: {{ user.profile.cell_phone }}</p>
                <p class="center">Hakkımda: {{ user.profile.about }}</p>
        </div>

    </div>




{% endblock %}